### ISSUE TITLE
Include API docs for RCM API

### ISSUE THREAD

**Issue by msehnout** [osbuild/legacy-website#2]
This depends on https://github.com/osbuild/osbuild-composer/pull/321

if we had the API specification file, we could generate HTML file from it like this:
```
 $ swagger-codegen generate -i docs/rcm-api.yaml -l html -o html/
```
and then include it on the website.

**Comment by dvdhrm** [comment]
I will close this for now, since we have been switching away from `swagger-codegen`. If there is a new agreement on which model to use, just ping me on `#osbuild` and I will gladly add it!
